version: '3.3'

services:
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - gcp-creds:/creds
      - .:/app
    working_dir: /app
    environment:
      - CLOUDSDK_CONFIG=/creds
      - GOOGLE_APLICATION_CREDENTIALS=/credentials/bym-backend-2350f39257af.json


volumes:
  gcp-creds: