version: '3.3'
services:
  backend:
    container_name: bym_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c ' python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    container_name: bym_db
    environment:
      MYSQL_DATABASE: bym
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306