# Generated by Django 4.1.3 on 2022-11-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100, unique=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bym_desk_app.usuario', unique=True)),
            ],
        ),
    ]
