# Generated by Django 4.1.3 on 2022-11-16 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bym_desk_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('analista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bym_desk_app.analista')),
                ('solicitante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bym_desk_app.usuario')),
            ],
        ),
    ]
