# Generated by Django 3.1.3 on 2022-11-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bym_desk_app', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analista',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('imagem', models.CharField(max_length=100)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bym_desk_app.ticket')),
            ],
        ),
    ]
